[[plugins]]
package = "@netlify/plugin-gatsby"

[build]
command = "gatsby build && rm -rf .cache/adapters/node_modules/.bin/download-msgpackr-prebuilds"
publish = "public"

[build.environment]
NETLIFY_BUILD_DEBUG = "true"